title: Alex Lindeman
description: >-
  The personal web site of Alex Lindeman,
  a dev-ops and software engineer
  from Washington, DC.

permalink: /journal/:slug
strict_front_matter: true
show_dir_listing: false

timezone: America/New_York

ignore:
  - .bundle
  - .gitignore
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

exclude:
  - journal

plugins:
  - jekyll-feed
  - jekyll-sitemap

defaults:
  - scope:
      path: ''
    values:
      layout: default
  - scope:
      type: 'posts'
    values:
      layout: journal
      section: journal
